on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
name: Depscan
jobs:
  depscan:
    name: depscan/ci
    runs-on: ubuntu-20.04
    steps:
    - uses: AppThreat/dep-scan-action@master
      with:
        # The target directory to be scanned. Optional.
        src: /github/workspa
        # Output file for the generated report. Optional.
        report_file: /github/workspace/reports/depscan.json
        # Must equal "I have sponsored OWASP-dep-scan" for action to run. Required.
        profile: generic
        thank_you: "I have not sponsored OWASP-dep-scan."
      env:
        VDB_HOME: ${{ github.workspace }}/db
        GITHUB_TOKEN: ${{ secrets.DEPSCAN_APP_TOKEN }}
